---
title: "2017-08-22-junior-schedule"
author: "James Diao"
date: "8/23/2017"
output: md_document
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
```
\---  
layout: post  
title: "Junior Schedule"  
date: 2017-08-22  
\---  

```{r}
kable(
  data.frame(
           FRESHMAN_FALL = c('FALL','CHEM 124 Organic Chemistry I', 'CHEM 222L Organic Chemistry Lab',
                             'BIOL 101/102 Intro Biology', 'PLSC 281 Issues in Bioethics', 'HLTH 230 Global Health'), 
           FRESHMAN_SPRING = c('SPRING','CHEM 125 Organic Chemistry II', 'CHEM 223L Organic Chemistry Lab II',
                               'BIOL 103/104 Intro Biology', 'MATH 120 Multivariable Calculus', 'ENGL 114 Writing Seminar'), 
           SOPHOMORE_FALL = c('FALL','SPAN 110 Elementary Spanish I', 'MB&B 300 Biochemistry I', 'PHYS 180 University Physics I', 
                              'PHYS 165L General Physics Lab I', 'STAT 238 Probability and Statistics'), 
           SOPHOMORE_SPRING = c('SPRING','SPAN 120 Elementary Spanish II', 'MB&B 301 Biochemistry II', 'ER&M 217 Intro Latino/a Studies', 
                                'PHYS 166L General Physics Lab II', ''), 
           JUNIOR_FALL = c('FALL','CHEM 332 Physical Chemistry I', 'MATH 222 Linear Algebra and Apps', 'CPSC 453 Machine Learning in Biology',
                           'ENGL 120 Reading/Writing the Modern Essay', 'MB&B 470 Research for Credit'), 
           JUNIOR_SPRING = c('SPRING','STAT 242 Theory of Statistics', 'STAT 230 Intro to Data Analysis', 'MB&B 452 Biological Data Science',
                             'PHYS 181 University Physics II', 'MB&B 471 Research for Credit')
           ) %>% t
)
```
